[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
chain_spec_path = "chain/westend-local/westend-local-spec-raw.json"
#chain_spec_path = "chain/3-auth-node-v0.9.10/genesis-raw.json"

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  command = "polkadot"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  command = "~/projects/ChainSafe/gossamer/bin/gossamer"
  validator = true
  args = ["--config", "./chain/westend-local/config-bob-min.toml", "--key bob", "--rpcmods", "system,author,chain,state,rpc,grandpa,offchain,childstate,syncstate,payment"]

  #[[relaychain.nodes]]
  #name = "charlie"
  #command = "~/projects/ChainSafe/gossamer/bin/gossamer"
  #validator = true
  #args = ["--config", "./chain/westend-local/config-charlie-min.toml","--key charlie", "--rpcmods", "system,#author,chain,state,rpc,grandpa,offchain,childstate,syncstate,payment"]
