[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
#default_command = "polkadot"
#default_args = [ "-lparachain=debug" ]
chain_spec_path = "chain/westend-local/westend-local-spec-raw.json"

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  command = "~/projects/ChainSafe/gossamer/bin/gossamer"
  validator = true
  args = ["--config", "./chain/westend-local/config-alice.toml", "--key alice", "--babe-lead", "--rpcmods", "system,author,chain,state,rpc,grandpa,offchain,childstate,syncstate,payment"]

  [[relaychain.nodes]]
  name = "bob"
  command = "polkadot"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  command = "~/projects/ChainSafe/gossamer/bin/gossamer"
  validator = true
  args = ["--config", "./chain/westend-local/config-charlie.toml","--key charlie", "--rpcmods", "system,author,chain,state,rpc,grandpa,offchain,childstate,syncstate,payment"]
