[global]
basepath = "~/.gossamer/dev_charlie"
log = "info"
metrics-address = ":9876"

[log]
core = ""
network = ""
rpc = ""
state = ""
runtime = ""
babe = ""
grandpa = ""
sync = ""
digest = ""

[init]
genesis = "./chain/dev/genesis-spec_test.json"

[account]
key = "charlie"
unlock = ""

[core]
roles = 4
babe-authority = true
grandpa-authority = true
babe-lead = false

[network]
port = 7003
nobootstrap = false
nomdns = false

[rpc]
enabled = true
ws = true
port = 8565
host = "localhost"
modules = ["system", "author", "chain", "state", "rpc", "grandpa", "offchain", "childstate", "syncstate", "payment"]
ws-port = 8566

[pprof]
enabled = false
listening-address = "localhost:6060"
block-rate = 0
mutex-rate = 0
